# Natural Language Processing

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('clean_data.csv')

## Cleaning the texts

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,10000):
  text = re.sub('[^a-zA-Z]', ' ', dataset['text'][i])
  text = text.lower()
  text=text.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
  text = ' '.join(text)
  corpus.append(text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
print(corpus)

['go villag pump suggest chang languag rfc set', 'anti greek nationali wikipedia hi alexikoua you not vandalis wikipedia edit fals inform may chauvinist not edit fals inform wikipedia nowher percent greek albania real inform censu not vandalis wikipedia milit idea', 'di hoe wasnt di violent lotteri ticket', 'better atabay not help ban vandal push pov', 'camelcas sicko not camelcas camelcas rule r baley mention inapplic', 'hi request arbitr wikipedia request arbitr trey stone davenbel wikipedia request arbitr trey stone davenbel evid mention evid present bring attent comment evid welcom sincer may utc', 'nonetheless lactos hemiacet group e g sucros trehalos lock acet', 'revert much want never say permiss attack lebanon', 'yo bag gucci still ugli hoe shut', 'thank would use ping thank not includ sentiment appreci time took add much appreci talk', 'pleas test sandbox thank jul utc', 'scott fivelson hello believ made consider progress ad credibl scott page includ ad refer would care recons

## Creating the Bag of Words model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 150000)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:10000, 0].values

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting the Test results

In [ ]:
print(X_test)
y_pred =classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 1]
 [1 1]
 [0 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[1604    8]
 [ 120  268]]


0.936